<?php get_header(); ?>
<main id="main-content">
<section class="hero"><div class="container hero-grid">
  <div class="reveal"><span class="eyebrow">ZAGGREGATE · Zagreb × Lausanne</span><h1>Developing retrofit strategies for <span>historical masonry building aggregates</span> in Zagreb.</h1><p class="hero-statement"><?php echo esc_html(get_theme_mod('hero_title', 'Rethinking seismic retrofit at the scale of the whole building row.')); ?></p><p class="hero-copy"><?php echo esc_html(get_theme_mod('hero_intro', 'ZAGGREGATE treats historic masonry rows as interacting structural systems. Field evidence, experiments and validated numerical models are combined to develop holistic, heritage-compatible strategies that reduce seismic risk across the entire aggregate—not only one building.')); ?></p><div class="hero-principles" aria-label="Project principles"><span>Evidence-based interventions</span><span>Tools for engineering practice</span><span>Open data &amp; education</span></div><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/project-overview/')); ?>">Explore the project →</a><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/open-positions/')); ?>">Join our team</a></div><div class="hero-meta"><div class="hero-stat"><strong>4 years</strong><span>Integrated programme</span></div><div class="hero-stat"><strong>6 WPs</strong><span>From field to guidance</span></div><div class="hero-stat"><strong>2 institutions</strong><span>One research team</span></div></div></div>
  <div class="visual-card reveal">
    <figure class="hero-project-visual"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/project/zaggregate-project-visual.png'); ?>" alt="ZAGGREGATE Project visual connecting Zagreb and Lausanne project partners"></figure>
    <div class="hero-building-frame"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/zagreb-row.svg'); ?>" alt="Stylised historic Zagreb masonry building aggregate"></div>
    <div class="float-note"><strong>Closing the guidance gap.</strong><span>Current seismic codes lack specific guidance for building aggregates. ZAGGREGATE develops practical recommendations for assessment and retrofit.</span></div>
  </div>
</div></section>

<section class="section home-explore" id="explore"><div class="container"><div class="section-head reveal"><span class="eyebrow">Explore ZAGGREGATE</span><h2>Discover the project.</h2><p>Learn about the research challenge, six work packages, the Zagreb–Lausanne collaboration and opportunities to join the team.</p></div><div class="home-path-grid">
  <a class="home-path-card reveal" href="<?php echo esc_url(home_url('/project-overview/')); ?>"><span>01</span><h3>Project overview</h3><p>The challenge, earthquake evidence, objectives and expected engineering outcomes.</p><strong>Discover the project →</strong></a>
  <a class="home-path-card home-path-card--research reveal" href="<?php echo esc_url(home_url('/research-programme/')); ?>"><span>02</span><h3>Research programme</h3><p>The complete workflow, all six work packages and the four-year roadmap.</p><strong>Explore the research →</strong></a>
  <a class="home-path-card home-path-card--team reveal" href="<?php echo esc_url(home_url('/team-partners/')); ?>"><span>03</span><h3>Team &amp; partners</h3><p>The Zagreb–Lausanne collaboration, project funder and institutional partners.</p><strong>Meet the collaboration →</strong></a>
  <a class="home-path-card home-path-card--positions reveal" href="<?php echo esc_url(home_url('/open-positions/')); ?>"><span>04</span><h3>Open positions</h3><p>Doctoral and postdoctoral opportunities at the University of Zagreb and EPFL.</p><strong>View opportunities →</strong></a>
</div></div></section>

<section class="home-opportunities" id="positions"><div class="container"><div class="home-opportunities-head reveal"><div><span class="eyebrow">Current opportunities</span><h2>Join the ZAGGREGATE research team.</h2></div><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/open-positions/')); ?>">View all positions →</a></div><div class="opportunity-brief-grid">
  <article class="opportunity-brief reveal"><span>Zagreb · University of Zagreb</span><h3>3 PhD and 2 postdoctoral positions</h3><p>English application guidance is available for international candidates.</p><div><a class="btn btn-primary" href="<?php echo esc_url(home_url('/university-of-zagreb-positions/')); ?>">Details &amp; how to apply →</a></div></article>
  <article class="opportunity-brief opportunity-brief--epfl reveal"><span>Lausanne · EPFL EESD</span><h3>2 PhD positions</h3><p>Official EPFL call. Application deadline: 30 September 2026.</p><div><a class="btn btn-primary" target="_blank" rel="noopener" href="https://careers.epfl.ch/job/Lausanne-2-PhD-Positions-in-Earthquake-Engineering-Structural-Engineering-%28ENACEESD%29/1164923655/">View official call ↗</a></div></article>
</div></div></section>

<section class="section news" id="news"><div class="container"><div class="section-head reveal"><span class="eyebrow">News &amp; updates</span><h2>Join the ZAGGREGATE research team.</h2></div><div class="news-side home-news-grid">
  <article class="mini-news recruitment-news recruitment-news--epfl reveal"><span class="date">EPFL · Applications open</span><h3>Two PhD positions in Earthquake Engineering / Structural Engineering</h3><p>EPFL EESD is recruiting two doctoral researchers in Lausanne to contribute to the experimental and numerical investigation of historical masonry building aggregates.</p><div class="news-meta"><span>Application deadline</span><strong>30 September 2026</strong></div><a class="btn btn-secondary" target="_blank" rel="noopener" href="https://careers.epfl.ch/job/Lausanne-2-PhD-Positions-in-Earthquake-Engineering-Structural-Engineering-%28ENACEESD%29/1164923655/">View the official EPFL call ↗</a></article>
  <article class="mini-news recruitment-news recruitment-news--unizg reveal"><span class="date">University of Zagreb · Applications open</span><h3>Three PhD and two postdoctoral positions</h3><p>The Faculty of Civil Engineering is recruiting researchers in Zagreb. English application guidance is available for international candidates.</p><div class="news-meta"><span>Application deadlines</span><strong>10 &amp; 30 September 2026</strong></div><a class="btn btn-secondary" href="<?php echo esc_url(home_url('/university-of-zagreb-positions/')); ?>">English details &amp; how to apply →</a></article>
</div></div></section>
<section class="contact" id="contact"><div class="container"><div class="contact-panel contact-panel--project reveal"><div class="contact-intro"><span class="eyebrow">Project coordinators</span><h2>Let’s connect.</h2><p>Contact the project coordinator in Zagreb or Lausanne.</p></div><div class="project-contact-grid">
  <article class="project-contact-card"><span class="project-contact-place">Zagreb · University of Zagreb</span><h3>Maja Baniček</h3><p>Croatian Centre for Earthquake Engineering<br>University of Zagreb</p><a href="mailto:maja.banicek@grad.unizg.hr">maja.banicek@grad.unizg.hr</a><a class="project-contact-website" href="https://www.grad.unizg.hr/en/maja.banicek" target="_blank" rel="noopener">Faculty profile ↗</a></article>
  <article class="project-contact-card project-contact-card--epfl"><span class="project-contact-place">Lausanne · EPFL</span><h3>Igor Tomić</h3><p>Earthquake Engineering and Structural Dynamics Laboratory (EESD)</p><a href="mailto:igor.tomic@epfl.ch">igor.tomic@epfl.ch</a></article>
</div></div></div></section>
</main>
<?php get_footer(); ?>
