<?php get_header(); ?>
<main id="main-content">
<section class="content-hero"><div class="container"><span class="eyebrow">Research programme</span><h1>Six work packages, one integrated path from evidence to practice.</h1><p>The four-year programme combines in-situ data, experimental campaigns, numerical modelling, vulnerability assessment and retrofit concepts.</p></div></section>

<section class="section research" id="work-packages"><div class="container">
  <figure class="research-overview reveal"><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/project/project-workflow.png'); ?>" target="_blank" rel="noopener" aria-label="Open the full ZAGGREGATE work package overview"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/project/project-workflow.png'); ?>" alt="Diagram showing the six ZAGGREGATE work packages and links between data acquisition, experiments, numerical modelling and conservation"></a><figcaption><strong>One integrated research programme.</strong> Field data, experiments, numerical modelling and conservation expertise feed into one another throughout the project.</figcaption></figure>
  <div class="wp-grid">
    <article class="wp-card reveal" data-wp="1"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp1-building-typologies.SVG'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp1-building-typologies.SVG'); ?>" alt="WP1 building typologies and in-situ data"></a></figure><div class="wp-body"><span class="wp-tag">WP1</span><h2>Building typologies &amp; in-situ data</h2><p>WP1 builds the evidence base for the project. Field surveys and GIS data document geometry, structural systems, construction history, position in the row and interaction with adjacent buildings.</p><ul><li>Typology and exposure database</li><li>Damage-pattern classification</li><li>Ambient-vibration, sonic, flat-jack and gap measurements</li></ul><strong class="wp-output">Output: calibrated inputs for aggregate-level assessment</strong></div></article>
    <article class="wp-card reveal" data-wp="2"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp2-material-characterisation.svg'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp2-material-characterisation.svg'); ?>" alt="WP2 material and component characterisation"></a></figure><div class="wp-body"><span class="wp-tag">WP2</span><h2>Material &amp; component characterisation</h2><p>WP2 studies how historic brick, mortar, walls and connections behave under load. Laboratory campaigns are paired with numerical models so measured behaviour can be transferred to complete aggregates.</p><ul><li>Mechanical properties and uncertainty</li><li>Cyclic in-plane tests on walls and partitions</li><li>Calibration of models and strengthening solutions</li></ul><strong class="wp-output">Output: validated material and component models</strong></div></article>
    <article class="wp-card reveal" data-wp="3"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp3-out-of-plane.svg'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp3-out-of-plane.svg'); ?>" alt="WP3 out-of-plane failure modelling"></a></figure><div class="wp-body"><span class="wp-tag">WP3</span><h2>Out-of-plane failures in aggregates</h2><p>WP3 investigates façade and gable-wall failures, including interaction between in-plane damage and out-of-plane instability. Observed damage identifies and validates likely failure mechanisms.</p><ul><li>Database of out-of-plane failures</li><li>Discrete-element and kinematic modelling</li><li>Comparison with Eurocode 8 provisions</li></ul><strong class="wp-output">Output: validated mechanisms and modelling recommendations</strong></div></article>
    <article class="wp-card reveal" data-wp="4"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp4-shake-table.svg'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp4-shake-table.svg'); ?>" alt="WP4 shake-table test and blind prediction"></a></figure><div class="wp-body"><span class="wp-tag">WP4</span><h2>Shake-table test &amp; blind prediction</h2><p>WP4 provides the large-scale experimental benchmark. A representative Zagreb-type masonry building is tested under bidirectional earthquake excitation after international teams submit blind predictions.</p><ul><li>Specimen design and numerical pre-testing</li><li>Blind prediction and post-diction competition</li><li>Open experimental data and benchmarking</li></ul><strong class="wp-output">Output: benchmarked models and improved guidance</strong></div></article>
    <article class="wp-card reveal" data-wp="5"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp5-vulnerability.svg'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp5-vulnerability.svg'); ?>" alt="WP5 vulnerability assessment"></a></figure><div class="wp-body"><span class="wp-tag">WP5</span><h2>Vulnerability of unretrofitted aggregates</h2><p>WP5 moves from individual analyses to vulnerability and fragility at aggregate and city scale, examining position, neighbouring units and acceleration amplification.</p><ul><li>Unit- and aggregate-level fragility curves</li><li>Efficient earthquake intensity measures</li><li>City-scale risk scenarios for Zagreb</li></ul><strong class="wp-output">Output: quantified vulnerability of existing aggregates</strong></div></article>
    <article class="wp-card reveal" data-wp="6"><figure><a href="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp6-retrofit.svg'); ?>" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/work-packages/slides/wp6-retrofit.svg'); ?>" alt="WP6 retrofit concepts and guidance"></a></figure><div class="wp-body"><span class="wp-tag">WP6</span><h2>Retrofit concepts &amp; guidance</h2><p>WP6 compares isolated and coordinated interventions to improve safety without transferring risk to neighbouring buildings. Effectiveness, feasibility and compatibility with historic fabric are considered together.</p><ul><li>Database of applicable retrofit techniques</li><li>Parametric studies of strengthened rows</li><li>Assessment and design guidance</li></ul><strong class="wp-output">Output: practical, risk-informed retrofit guidance</strong></div></article>
  </div>
</div></section>

<section class="section roadmap" id="roadmap"><div class="container"><div class="section-head reveal"><span class="eyebrow">Four-year roadmap</span><h2>From field evidence to guidance and impact.</h2><p>The work packages overlap by design: measurements inform models, experiments validate them, and vulnerability studies shape retrofit concepts.</p></div><div class="roadmap-track reveal" aria-label="Four-year project roadmap"><div class="roadmap-years"><span>Year 1</span><span>Year 2</span><span>Year 3</span><span>Year 4</span></div><div class="roadmap-row"><b>WP1</b><span style="--start:0;--span:2">Field data &amp; typologies</span></div><div class="roadmap-row"><b>WP2</b><span style="--start:0;--span:3">Laboratory campaigns</span></div><div class="roadmap-row"><b>WP3</b><span style="--start:0;--span:4">Out-of-plane modelling</span></div><div class="roadmap-row"><b>WP4</b><span style="--start:1;--span:3">Shake-table test &amp; prediction</span></div><div class="roadmap-row"><b>WP5</b><span style="--start:0;--span:4">Vulnerability assessment</span></div><div class="roadmap-row"><b>WP6</b><span style="--start:1;--span:3">Retrofit concepts &amp; guidance</span></div></div></div></section>
<section class="page-next"><div class="container"><span>Meet the collaboration</span><a href="<?php echo esc_url(home_url('/team-partners/')); ?>">Explore the team &amp; partners →</a></div></section>
</main>
<?php get_footer(); ?>
