<?php get_header(); ?>
<main id="main-content">
<section class="content-hero"><div class="container"><span class="eyebrow">Team &amp; partners</span><h1>Zagreb field expertise meets Lausanne experimental research.</h1><p>University of Zagreb FCE / CCEE and EPFL EESD form one integrated research team, supported by Croatian institutions responsible for science, heritage and the built environment.</p></div></section>

<section class="section partners" id="collaboration"><div class="container">
  <div class="section-head reveal"><span class="eyebrow">Project leadership</span><h2>Jointly led in Zagreb and Lausanne.</h2><p>Each institution has a project leader and a project coordinator, ensuring close scientific and organisational collaboration throughout the programme.</p></div>
  <div class="partner-grid"><article class="partner-card reveal"><span class="partner-label">Zagreb</span><h2>University of Zagreb Faculty of Civil Engineering</h2><div class="partner-people" aria-label="University of Zagreb project leadership"><div class="team-person"><strong>Josip Atalić</strong><span>Project leader</span></div><div class="team-person"><strong>Maja Baniček</strong><span>Project coordinator</span></div></div><div class="additional-team" aria-label="Additional University of Zagreb project team members"><span class="additional-team-label">Project team</span><div><span>Mario Uroš</span><span>Marta Šavor Novak</span><span>Marija Demšić</span></div></div><ul><li>Post-earthquake damage assessment and field experience</li><li>Seismic risk and vulnerability of masonry aggregates</li><li>Numerical modelling and engineering implementation</li></ul></article><div class="exchange"><span>↔</span>Researcher exchanges<br>Co-supervised PhDs<br>Shared data</div><article class="partner-card red reveal"><span class="partner-label">Lausanne</span><h2>EPFL EESD</h2><div class="partner-people" aria-label="EPFL EESD project leadership"><div class="team-person"><strong>Katrin Beyer</strong><span>Project leader</span></div><div class="team-person"><strong>Igor Tomić</strong><span>Project coordinator</span></div></div><ul><li>Large-scale shake-table testing</li><li>Experimental campaigns and material characterisation</li><li>Advanced modelling, benchmarking and blind prediction</li></ul></article></div>
  <figure class="team-visit reveal"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/project/zagreb-epfl-team-visit.jpg'); ?>" alt="Researchers from Zagreb and EPFL during a project visit in Zagreb"><figcaption><strong>Building the collaboration.</strong> EPFL EESD team visit to Zagreb, July 2021 — field exchange that helped shape the joint research programme.</figcaption></figure>
</div></section>

<section class="section governance" id="governance"><div class="container">
  <div class="section-head reveal"><span class="eyebrow">Project governance &amp; scientific network</span><h2>Connecting science, engineering, policy and heritage protection.</h2><p>The project is supported by a three-level governance and collaboration structure that brings together ministries, international researchers, Croatian experts and professional stakeholders.</p></div>
  <div class="governance-stack">
    <article class="governance-tier governance-tier--steering reveal">
      <div class="governance-index"><span>01</span><small>Governance</small></div>
      <div class="governance-content"><div class="governance-heading"><div><span class="governance-kicker">Strategic oversight</span><h3>Steering Committee</h3></div><span class="governance-frequency">Meetings every 6 months</span></div>
        <div class="steering-grid"><a href="https://mzom.gov.hr/en" target="_blank" rel="noopener"><strong>Ministry of Science, Education and Youth</strong><span>Project funder</span></a><a href="https://min-kulture.gov.hr/en" target="_blank" rel="noopener"><strong>Ministry of Culture and Media</strong><span>Heritage policy</span></a><a href="https://mpgi.gov.hr/en" target="_blank" rel="noopener"><strong>Ministry of Physical Planning, Construction and State Assets</strong><span>Built environment policy</span></a></div>
      </div>
    </article>
    <article class="governance-tier governance-tier--advisory reveal">
      <div class="governance-index"><span>02</span><small>Advisory</small></div>
      <div class="governance-content"><div class="governance-heading"><div><span class="governance-kicker">Independent expertise</span><h3>International Advisory Board</h3></div></div>
        <div class="advisory-columns"><section><h4>International experts</h4><div class="people-list"><div><strong>Frédéric Dubois</strong><span>LMGC, CNRS</span></div><div><strong>Serena Cattari</strong><span>University of Genoa</span></div><div><strong>Sergio Lagomarsino</strong><span>University of Genoa</span></div><div><strong>Andrea Penna</strong><span>University of Pavia</span></div></div><p class="network-note">Additional international experts to be confirmed.</p></section><section><h4>Croatian experts &amp; stakeholders</h4><div class="stakeholder-grid"><span>Boris Trogrlić</span><span>Bojan Milovanović</span><span>Juraj Pojatina</span><span>Tomislav Petrinec <small>Ministry of Culture and Media</small></span><span>Martina Vujasinović</span><span>Ante Buzov</span><span>Mario Todorić</span><span>Josip Galić</span></div><p class="network-note">Additional experts and stakeholders to be confirmed.</p></section></div>
      </div>
    </article>
    <article class="governance-tier governance-tier--network reveal">
      <div class="governance-index"><span>03</span><small>Network</small></div>
      <div class="governance-content"><div class="governance-heading"><div><span class="governance-kicker">Research collaboration</span><h3>Scientific Collaborators &amp; Partners</h3></div></div>
        <div class="collaborator-grid"><div><strong>Frédéric Dubois</strong><span>LMGC, CNRS</span></div><div><strong>Serena Cattari</strong><span>University of Genoa</span></div><div><strong>Sergio Lagomarsino</strong><span>University of Genoa</span></div><div><strong>Andrea Penna</strong><span>University of Pavia</span></div><div class="collaborator-group"><strong>Extended project network</strong><span>Croatian research teams, professional partners, institutional collaborators and young researchers</span></div></div><p class="network-note">Additional collaborators will be added as the project network develops.</p>
      </div>
    </article>
  </div>
</div></section>

<section class="section institutional-support" id="institutions"><div class="container">
  <div class="section-head reveal"><span class="eyebrow">Funding &amp; institutional partners</span><h2>Connecting science, heritage and reconstruction.</h2><p>ZAGGREGATE is funded by the Republic of Croatia Ministry of Science, Education and Youth and developed with institutional partners responsible for cultural heritage and the built environment.</p></div>
  <a class="funder-card institution-link reveal" href="https://mzom.gov.hr/en" target="_blank" rel="noopener"><div class="support-role">Project funded by</div><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/ministry-science-education-youth.png'); ?>" alt="Republic of Croatia Ministry of Science, Education and Youth logo"><div><strong>Republic of Croatia</strong><span>Ministry of Science, Education and Youth</span></div></a>
  <div class="support-group reveal"><h3>Institutional partners</h3><div class="ministry-grid"><a class="institution-card ministry-card institution-link" href="https://min-kulture.gov.hr/en" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/ministry-culture-media.jpg'); ?>" alt="Republic of Croatia Ministry of Culture and Media logo"><div><strong>Ministry of Culture and Media</strong><span>Heritage protection and reconstruction</span></div></a><a class="institution-card ministry-card institution-link" href="https://mpgi.gov.hr/en" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/ministry-construction-state-assets.png'); ?>" alt="Republic of Croatia Ministry of Physical Planning, Construction and State Assets logo"><div><strong>Ministry of Physical Planning, Construction and State Assets</strong><span>Built environment and reconstruction policy</span></div></a></div></div>
  <div class="support-group research-institutions reveal"><h3>Research institutions</h3><div class="institution-grid">
    <a class="institution-card institution-link" href="https://www.unizg.hr/" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/university-zagreb.png'); ?>" alt="University of Zagreb logo"><div><strong>University of Zagreb</strong><span>Sveučilište u Zagrebu</span></div></a>
    <a class="institution-card institution-link" href="https://www.grad.unizg.hr/" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/unizg-fce.png'); ?>" alt="University of Zagreb Faculty of Civil Engineering logo"><div><strong>Faculty of Civil Engineering</strong><span>University of Zagreb</span></div></a>
    <a class="institution-card institution-link" href="https://gfzg.hcpi.hr/" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/ccee.png'); ?>" alt="Croatian Centre for Earthquake Engineering logo"><div><strong>Croatian Centre for Earthquake Engineering</strong><span>CCEE</span></div></a>
    <a class="institution-card institution-card--epfl institution-link" href="https://www.epfl.ch/en/" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/epfl.png'); ?>" alt="EPFL logo"><div><strong>EPFL</strong><span>École polytechnique fédérale de Lausanne</span></div></a>
    <a class="institution-card institution-card--eesd institution-link" href="https://www.epfl.ch/labs/eesd/" target="_blank" rel="noopener"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/partners/eesd.png'); ?>" alt="EESD logo"><div><strong>Earthquake Engineering and Structural Dynamics Laboratory</strong><span>EESD · EPFL</span></div></a>
  </div></div>
</div></section>
<section class="contact" id="contact"><div class="container"><div class="contact-panel contact-panel--project reveal"><div class="contact-intro"><span class="eyebrow">Project coordinators</span><h2>Let’s connect.</h2><p>Contact the project coordinator in Zagreb or Lausanne.</p></div><div class="project-contact-grid">
  <article class="project-contact-card"><span class="project-contact-place">Zagreb · University of Zagreb</span><h3>Maja Baniček</h3><p>Croatian Centre for Earthquake Engineering<br>University of Zagreb</p><a href="mailto:maja.banicek@grad.unizg.hr">maja.banicek@grad.unizg.hr</a><a class="project-contact-website" href="https://www.grad.unizg.hr/en/maja.banicek" target="_blank" rel="noopener">Faculty profile ↗</a></article>
  <article class="project-contact-card project-contact-card--epfl"><span class="project-contact-place">Lausanne · EPFL</span><h3>Igor Tomić</h3><p>Earthquake Engineering and Structural Dynamics Laboratory (EESD)</p><a href="mailto:igor.tomic@epfl.ch">igor.tomic@epfl.ch</a><a class="project-contact-website" href="https://people.epfl.ch/igor.tomic?lang=en" target="_blank" rel="noopener">EPFL profile ↗</a></article>
</div></div></div></section>
</main>
<?php get_footer(); ?>
