<?php get_header(); ?>
<main id="main-content">
<section class="content-hero content-hero--positions"><div class="container"><span class="eyebrow">Open positions</span><h1>Build your research career with ZAGGREGATE.</h1><p>Applications are open for five doctoral and two postdoctoral positions across Zagreb and Lausanne. A third University of Zagreb postdoctoral call is expected in September 2026.</p><div class="position-summary"><span><strong>5</strong> doctoral positions open</span><span><strong>2</strong> postdoctoral positions open</span><span><strong>2</strong> research locations</span></div></div></section>

<section class="hiring positions-page" id="zagreb"><div class="container"><div class="hiring-panel reveal">
  <section class="position-location-group" aria-labelledby="positions-zagreb"><div class="position-location-head"><div><span class="position-place">Zagreb · Croatia</span><h2 id="positions-zagreb">University of Zagreb</h2></div><div class="position-statuses"><span class="position-count position-count--open">5 positions open</span><span class="position-count position-count--upcoming">1 call expected September 2026</span></div></div>
  <div class="position-grid position-grid--zagreb">
    <article class="position-card doctoral"><div class="position-card-head"><span class="position-badge">PhD 1</span><span class="position-host">UniZG</span></div><h3>Damage patterns and aggregate-scale models</h3><p>From observed earthquake damage to calibrated models of masonry building rows.</p><ul><li>Material testing, NDT and operational modal analysis</li><li>Damage-pattern database and empirical relationships</li><li>OpenSees models of units and aggregates</li></ul></article>
    <article class="position-card doctoral"><div class="position-card-head"><span class="position-badge">PhD 4</span><span class="position-host">UniZG</span></div><h3>Out-of-plane demand and capacity</h3><p>Modelling realistic out-of-plane mechanisms within interacting building rows.</p><ul><li>Aggregate-specific seismic demand</li><li>In-plane–out-of-plane interaction</li><li>Fragility functions and practical checks</li></ul></article>
    <article class="position-card doctoral"><div class="position-card-head"><span class="position-badge">PhD 5</span><span class="position-host">UniZG</span></div><h3>Eurocode 8 and shake-table benchmarking</h3><p>Testing current assessment approaches for historical aggregates.</p><ul><li>Shake-table test planning and execution</li><li>Blind prediction and post-diction benchmark</li><li>EC8 Part 3 evaluation</li></ul></article>
    <article class="position-card postdoc"><div class="position-card-head"><span class="position-badge">Postdoc 1</span><span class="position-host">UniZG</span></div><h3>In-situ testing and model calibration</h3><p>Identifying how adjacent masonry buildings interact through field measurements.</p><ul><li>NDT and operational modal analysis</li><li>Connection stiffness identification</li><li>Calibrated numerical models</li></ul></article>
    <article class="position-card postdoc"><div class="position-card-head"><span class="position-badge">Postdoc 2</span><span class="position-host">UniZG</span></div><h3>Vulnerability, fragility and seismic risk</h3><p>Translating advanced aggregate models into risk information for Zagreb.</p><ul><li>Aggregate-specific vulnerability methodology</li><li>Fragility curves by position and configuration</li><li>Risk maps for unretrofitted and retrofitted aggregates</li></ul></article>
    <article class="position-card postdoc upcoming"><div class="position-card-head"><span class="position-badge">Postdoc 3</span><span class="position-host">Coming soon</span></div><h3>Assessment and retrofit guidance</h3><p>Synthesising project results into a practical framework for engineering decisions.</p><ul><li>Assessment and design guidelines</li><li>Case-study retrofit of a Zagreb aggregate</li><li>Knowledge transfer, workshops and professional education</li></ul><div class="position-availability">Call expected in September 2026</div></article>
  </div>
  <div class="position-callout"><div><span class="position-callout-label">University of Zagreb recruitment</span><h3>3 PhD and 2 Postdoctoral Positions</h3><p>English application guidance is available for international candidates.</p></div><div class="position-callout-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/university-of-zagreb-positions/')); ?>">English details &amp; how to apply →</a><a class="official-source-link" target="_blank" rel="noopener" href="<?php echo esc_url(get_theme_mod('official_calls_url', 'https://www.grad.unizg.hr/novosti_i_objave/natjecaji?@=2b5wh#news_71010')); ?>">Official Croatian call ↗</a></div></div>
  </section>
</div></div></section>

<section class="hiring positions-page positions-page--epfl" id="lausanne"><div class="container"><div class="hiring-panel reveal"><section class="position-location-group" aria-labelledby="positions-lausanne"><div class="position-location-head"><div><span class="position-place">Lausanne · Switzerland</span><h2 id="positions-lausanne">EPFL · EESD</h2></div><span class="position-count position-count--open">Applications open</span></div><div class="position-grid position-grid--two">
  <article class="position-card doctoral"><div class="position-card-head"><span class="position-badge">PhD 2</span><span class="position-host">EPFL</span></div><h3>Advanced numerical modelling of masonry aggregates</h3><p>Developing and validating models for assessment and retrofit of connected rows.</p><ul><li>Advanced modelling of masonry spandrels</li><li>Retrofitted-row models and parametric studies</li><li>Assessment guidance and intervention effectiveness</li></ul></article>
  <article class="position-card doctoral"><div class="position-card-head"><span class="position-badge">PhD 3</span><span class="position-host">EPFL</span></div><h3>Load-bearing and non-load-bearing wall interaction</h3><p>Studying partition and load-bearing walls before and after retrofit.</p><ul><li>Large-scale in-plane experimental campaigns</li><li>Mechanical and numerical connection models</li><li>Validation of strengthening interventions</li></ul></article>
  </div><div class="position-callout"><div><span class="position-callout-label">Official EPFL call · Reference 2305</span><h3>2 PhD Positions in Earthquake Engineering / Structural Engineering</h3><div class="position-deadline"><span>Application deadline</span><time datetime="2026-09-30">30 September 2026</time></div></div><a class="btn btn-primary" target="_blank" rel="noopener" href="https://careers.epfl.ch/job/Lausanne-2-PhD-Positions-in-Earthquake-Engineering-Structural-Engineering-%28ENACEESD%29/1164923655/">View the EPFL call &amp; apply →</a></div></section></div></div></section>
</main>
<?php get_footer(); ?>
